
package com.oracle.csm.soapjsonproxy.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapJsonProxyPortType", targetNamespace = "http://ws.soapjsonproxy.csm.oracle.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapJsonProxyPortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "callJson", targetNamespace = "http://ws.soapjsonproxy.csm.oracle.com/", className = "com.oracle.csm.soapjsonproxy.client.CallJson")
    @ResponseWrapper(localName = "callJsonResponse", targetNamespace = "http://ws.soapjsonproxy.csm.oracle.com/", className = "com.oracle.csm.soapjsonproxy.client.CallJsonResponse")
    @Action(input = "http://ws.soapjsonproxy.csm.oracle.com/SoapJsonProxyPortType/callJsonRequest", output = "http://ws.soapjsonproxy.csm.oracle.com/SoapJsonProxyPortType/callJsonResponse")
    public String callJson(
        @WebParam(name = "arg0", targetNamespace = "")
        Pessoa arg0);

}
