
package com.oracle.csm.soapjsonproxy.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapJsonProxyService", targetNamespace = "http://ws.soapjsonproxy.csm.oracle.com/", wsdlLocation = "http://localhost:7101/soapjsonproxy/SoapJsonProxyService?WSDL")
public class SoapJsonProxyService
    extends Service
{

    //http://129.152.132.107
    
    private final static URL SOAPJSONPROXYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPJSONPROXYSERVICE_EXCEPTION;
    private final static QName SOAPJSONPROXYSERVICE_QNAME = new QName("http://ws.soapjsonproxy.csm.oracle.com/", "SoapJsonProxyService");

    static {
        WebServiceException e = null;
        URL url = null;
        try {
            url = new URL(com.oracle.csm.soapjsonproxy.client.SoapJsonProxyService.class.getResource("."), "http://localhost:7101/soapjsonproxy/SoapJsonProxyService?WSDL");
        } catch (MalformedURLException murl) {
            e = new WebServiceException(murl);
        }
        SOAPJSONPROXYSERVICE_WSDL_LOCATION = url;
        SOAPJSONPROXYSERVICE_EXCEPTION = e;
    }

    public SoapJsonProxyService() {
        super(__getWsdlLocation(), SOAPJSONPROXYSERVICE_QNAME);
    }

    public SoapJsonProxyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPJSONPROXYSERVICE_QNAME, features);
    }

    public SoapJsonProxyService(URL wsdlLocation) {
        super(wsdlLocation, SOAPJSONPROXYSERVICE_QNAME);
    }

    public SoapJsonProxyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPJSONPROXYSERVICE_QNAME, features);
    }

    public SoapJsonProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapJsonProxyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapJsonProxyPortType
     */
    @WebEndpoint(name = "SoapJsonProxyPortTypePort")
    public SoapJsonProxyPortType getSoapJsonProxyPortTypePort() {
        return super.getPort(new QName("http://ws.soapjsonproxy.csm.oracle.com/", "SoapJsonProxyPortTypePort"), SoapJsonProxyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapJsonProxyPortType
     */
    @WebEndpoint(name = "SoapJsonProxyPortTypePort")
    public SoapJsonProxyPortType getSoapJsonProxyPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soapjsonproxy.csm.oracle.com/", "SoapJsonProxyPortTypePort"), SoapJsonProxyPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPJSONPROXYSERVICE_EXCEPTION!= null) {
            throw SOAPJSONPROXYSERVICE_EXCEPTION;
        }
        return SOAPJSONPROXYSERVICE_WSDL_LOCATION;
    }

}
